### ISSUE TITLE
MPS to JSON

### ISSUE THREAD

**Issue by smithaaron** [ehn-dcc-development/dgc-business-rules#80]
I'm not familiar with MPS so just checking I'm not missing something here. I know the MPS ReadMe states that exporting isn't supported at the moment "either to the staging repository, or elsewhere". But is there any means to output the rules to JSON currently?

**Comment by dslmeinte** [comment]
Correct: outputting the rules to JSON isn't implemented in this repository. The reason is not that it's difficult, but that it requires some extra dependencies to implement it in a good way. I wasn't decided on which dependencies to choose exactly, since that choice has some consequences for integration. At the time, it wasn't clear how integration should look like anyway.

So, now I'm interested in how you would want/like/need to use the MPS editor? Can you tell me more?

**Comment by smithaaron** [comment]
I was mainly investigating it due to curiosity, but my expectation was that it would be a system where a non-programmer person could edit and create rules, which could then be exported in the necessary JSON format for consumption by a validator app.

**Comment by dslmeinte** [comment]
Yeah, that would be the general idea. Personally, I would prefer to spend time rather on developing a true Web editor than on a MPS-based editor.

I _have_ implemented an export facility that relies on one external MPS component, and uses a Node.js program to do the actual exporting. I could try and make to some time to make that available, but it'd be in a “works on _my_ machine”-kind-of state.

**Comment by smithaaron** [comment]
I'd agree that a web editor would be much more useful. 

No need to go to any further effort on my account. As I said, I was mainly just checking that I wasn't missing something obvious :)

**Comment by dslmeinte** [comment]
Happy to bring some clarification!
