### ISSUE TITLE
How to validate covid cert?

### ISSUE THREAD

**Issue by aBuder** [ehn-dcc-development/dgc-business-rules#83]
In our flutter app we need to validate covid cert. But I’m a bit lost. Is there an guideline or how to validate these? Maybe an piece of code.

**Comment by dslmeinte** [comment]
Hi @aBuder , Business rules form only a small part of the process of validating a DCC (and it's pretty much right at the end). You might want to start here: https://github.com/ehn-dcc-development/overview
(It's a work-in-progress, so still a bit rough around the edges, but the detailed content behind the links is solid, and helpful.)

**Comment by ikbendewilliam** [comment]
Since you're talking about Flutter specifically, I think I can help you a bit further. We have the package on pub.dev https://pub.dev/packages/certlogic_dart 
How we handle it in our app is doing the following
- `validationRules` is a `List<ValidationRule>?` containing a list of certlogic json data [example of rules](https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/tree/main/EU)
- `actualValidationDateTime` is today, but we can switch it for debugging purposes
- `data` is a Map<String, dynamic> containing the valuesets etc
- We first check if the rule is still valid (we can update these remotely so we can switch on a specific date if the law changes).
- We throw away all null's (passed rules)
- In the end, we have an array with all failed rules. These contain human-friendly descriptions that we can show depending on the use-case (for example police can see why it failed, but someone at a bar can't).
```dart
    final data = {
      'payload': payload,
      'external': {
        'valueSets': _valueSets.toJson(),
        'validationClock': validationDateTime.toIso8601String(),
      },
    };
    final failedRules = validationRules
        ?.map((rule) {
          if (rule.validFrom.isAfter(actualValidationDateTime) || rule.validTo.isBefore(actualValidationDateTime)) return null;
          return CertLogic.evaluate(rule.logic, data) as bool == true ? null : rule;
        })
        .whereType<ValidationRule>()
        .toList();
    return failedRules ?? [];
```
Hope this helps

**Comment by dslmeinte** [comment]
I'm closing this issue. If you have any further questions, you know where to find us, I assume.
